import { useMemo, useState } from 'react';
import type { Severity } from '@fca/core';
import { useWorkspace } from '../state/WorkspaceContext';
import { Badge, Card, EmptyState, PageHeader } from '../components/ui/primitives';
import { FlagCard, InsightCard } from '../components/analysis/MetricViews';
import { AnomalyTrail, ContradictionPanel } from '../components/analysis/AnomalyTrail';
import { SENTIMENT_TONE } from '../lib/display';

type Tab = 'all' | 'risks' | 'positives' | 'insights';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

export default function Insights() {
  const { analysis } = useWorkspace();
  const [tab, setTab] = useState<Tab>('all');
  const [minSeverity, setMinSeverity] = useState<Severity>('info');

  const filteredFlags = useMemo(() => {
    if (!analysis) return [];
    const limit = SEVERITY_ORDER.indexOf(minSeverity);
    return analysis.redFlags.filter((f) => SEVERITY_ORDER.indexOf(f.severity) <= limit);
  }, [analysis, minSeverity]);

  if (!analysis) return null;
  const { redFlags, positiveSignals, insights, executiveSummary } = analysis;

  const counts = {
    critical: redFlags.filter((f) => f.severity === 'critical').length,
    high: redFlags.filter((f) => f.severity === 'high').length,
    medium: redFlags.filter((f) => f.severity === 'medium').length,
    low: redFlags.filter((f) => f.severity === 'low').length,
  };

  const showRisks = tab === 'all' || tab === 'risks';
  const showPositives = tab === 'all' || tab === 'positives';
  const showInsights = tab === 'all' || tab === 'insights';

  return (
    <div className="space-y-5">
      <PageHeader
        title="Insights & Red Flags"
        description="Findings generated by the rule engine and the insight engine from the calculated metrics. Every statement carries the calculation behind it — use “View calculation” on any card to see the exact numbers it rests on."
      />

      <Card title="Executive summary" description="The most material observations, prioritised rather than exhaustive.">
        <p className="text-[13px] font-semibold text-ink-900 dark:text-ink-50">{executiveSummary.headline}</p>
        <p className="mt-1.5 text-[12.5px] leading-relaxed text-ink-700 dark:text-ink-300">{executiveSummary.overallAssessment}</p>

        {executiveSummary.takeaways.length > 0 && (
          <>
            <p className="label-caps mt-4">Most important takeaways</p>
            <ul className="mt-1.5 space-y-1.5">
              {executiveSummary.takeaways.map((takeaway, i) => (
                <li key={i} className="flex gap-2 text-[12.5px] leading-relaxed text-ink-700 dark:text-ink-300">
                  <span className="text-accent-500" aria-hidden="true">▸</span>
                  {takeaway}
                </li>
              ))}
            </ul>
          </>
        )}

        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {executiveSummary.sections.map((section) => (
            <div key={section.key} className="rounded-xl bg-ink-500/[0.06] px-3 py-2 dark:bg-ink-400/[0.08]">
              <div className="flex items-center justify-between gap-2">
                <p className="text-[12.5px] font-semibold text-ink-900 dark:text-ink-100">{section.label}</p>
                <Badge tone={SENTIMENT_TONE[section.sentiment]}>{section.sentiment}</Badge>
              </div>
              <p className="mt-1 text-[12px] leading-relaxed text-ink-600 dark:text-ink-400">{section.body}</p>
            </div>
          ))}
        </div>
      </Card>

      <ContradictionPanel analysis={analysis} />

      <AnomalyTrail analysis={analysis} />

      <Card padded={false}>
        <div className="flex flex-wrap items-center justify-between gap-3 px-3 py-2">
          <div className="flex flex-wrap gap-1" role="tablist" aria-label="Finding type">
            {([
              { key: 'all', label: `All (${redFlags.length + positiveSignals.length + insights.length})` },
              { key: 'risks', label: `Red flags (${redFlags.length})` },
              { key: 'positives', label: `Positive signals (${positiveSignals.length})` },
              { key: 'insights', label: `Insights (${insights.length})` },
            ] as const).map((option) => (
              <button
                key={option.key}
                type="button"
                role="tab"
                aria-selected={tab === option.key}
                onClick={() => setTab(option.key)}
                className={`rounded px-2.5 py-1 text-[12.5px] transition-colors ${
                  tab === option.key ? 'bg-accent-700 font-medium text-white' : 'text-ink-600 hover:bg-ink-100 dark:text-ink-300 dark:hover:bg-ink-800'
                }`}
              >
                {option.label}
              </button>
            ))}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {counts.critical > 0 && <Badge tone="negative">{counts.critical} critical</Badge>}
            {counts.high > 0 && <Badge tone="negative">{counts.high} high</Badge>}
            {counts.medium > 0 && <Badge tone="caution">{counts.medium} medium</Badge>}
            {counts.low > 0 && <Badge tone="neutral">{counts.low} low</Badge>}
            {showRisks && redFlags.length > 0 && (
              <select
                className="input w-auto py-1"
                value={minSeverity}
                onChange={(e) => setMinSeverity(e.target.value as Severity)}
                aria-label="Minimum severity"
              >
                <option value="info">All severities</option>
                <option value="low">Low and above</option>
                <option value="medium">Medium and above</option>
                <option value="high">High and above</option>
                <option value="critical">Critical only</option>
              </select>
            )}
          </div>
        </div>
      </Card>

      {showRisks && (
        <section>
          <h2 className="mb-2 text-[13px] font-semibold text-ink-900 dark:text-ink-50">
            Red flags
            <span className="ml-2 text-2xs font-normal text-ink-500">rule-based risk findings</span>
          </h2>
          {filteredFlags.length === 0 ? (
            <EmptyState
              title={redFlags.length === 0 ? 'No red flags were raised' : 'No red flags at this severity'}
              message={
                redFlags.length === 0
                  ? 'No rule in the risk engine was triggered by this data. That is not the same as a clean bill of health: check the Data Quality panel for metrics that could not be calculated, since a rule cannot fire on data it does not have.'
                  : 'Lower the severity filter to see the remaining findings.'
              }
            />
          ) : (
            <div className="grid gap-3 lg:grid-cols-2">
              {filteredFlags.map((flag) => <FlagCard key={flag.id} flag={flag} />)}
            </div>
          )}
        </section>
      )}

      {showPositives && (
        <section>
          <h2 className="mb-2 text-[13px] font-semibold text-ink-900 dark:text-ink-50">
            Positive signals
            <span className="ml-2 text-2xs font-normal text-ink-500">favourable developments supported by the data</span>
          </h2>
          {positiveSignals.length === 0 ? (
            <EmptyState
              title="No positive signals were raised"
              message="No positive-signal rule was triggered by this data. Each rule requires specific evidence — for example, three consecutive periods of free cash flow growth — and stays silent when the data does not support it."
            />
          ) : (
            <div className="grid gap-3 lg:grid-cols-2">
              {positiveSignals.map((signal) => <FlagCard key={signal.id} flag={signal} />)}
            </div>
          )}
        </section>
      )}

      {showInsights && (
        <section>
          <h2 className="mb-2 text-[13px] font-semibold text-ink-900 dark:text-ink-50">
            Analyst insights
            <span className="ml-2 text-2xs font-normal text-ink-500">written interpretation of the calculated metrics</span>
          </h2>
          <div className="grid gap-3 lg:grid-cols-2">
            {insights.map((insight) => <InsightCard key={insight.id} insight={insight} />)}
          </div>
        </section>
      )}

      <Card>
        <p className="text-2xs leading-relaxed text-ink-500 dark:text-ink-400">
          Findings are produced by deterministic rules from the calculated metrics, not by a language model. Where the data
          establishes a relationship, the wording states it; where it only suggests one, the wording says “may indicate”,
          “could suggest” or “warrants investigation”. Every threshold that triggered a rule is shown on the card and can be
          changed in Settings.
        </p>
      </Card>
    </div>
  );
}
